name: 报告错误的解法代码
title: "[bug] {这里替换为出错的力扣题号和题目} {这里替换为出错的编程语言}"
description: 
labels: [ "code bug" ]
body:
  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        请先搜索 [issues](https://github.com/labuladong/fucking-algorithm/issues) 确保你提的这个 bug 还没有被提交过。
      options:
        - label: >
            我已经搜索过 [issues](https://github.com/labuladong/fucking-algorithm/issues)，没有发现相同的 bug。
          required: true
  - type: input
    attributes:
      label: 出错的题目链接
      description: |
        输入力扣的题目链接
      placeholder: e.g. https://leetcode.cn/problems/search-a-2d-matrix/
    validations:
      required: true
  - type: textarea
    attributes:
      label: 报错信息
      description: |
        把出错的原因复制粘贴在这里
      value: |
        <!-- 把报错粘贴到下面的 ``` 块中 -->
        ```

        ```
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 你是否愿意提交 PR 修复这个 bug？
      description: >
        PR 规范 [见这里](https://github.com/labuladong/fucking-algorithm/issues/1113)，欢迎成为本仓库的 contributor！
      options:
        - label: 我愿意！
  - type: markdown
    attributes:
      value: "感谢你的支持，刷题全家桶会因你变得越来越好！"